name: API report

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  report:

    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check files
        run: ls built

      - name: API report
        run: npm run api-prod

      - name: Create Pull Request
        if: failure()
        run: |
          BASE_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo ${BASE_BRANCH}
          HEAD_BRANCH=api-report-$(git rev-parse --short HEAD)
          echo ${HEAD_BRANCH}
          git config user.email "cicada1003@gmail.com"
          git config user.name "AiScript api report bot"
          git switch -c ${HEAD_BRANCH}
          npm run api
          git add etc
          git commit -m'api report'
          git remote add target ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git
          git push -f -u target ${HEAD_BRANCH}
          gh pr create --fill \
            --head "target:${HEAD_BRANCH}" \
            --base "origin:${BASE_BRANCH}"

      - name: Show report
        if: always()
        run: cat temp/aiscript.api.md
