name: Publish on Pushes

on:
  push:
    branches:
      - master
      - aiscript-next
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ secrets.NPM_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20.x

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Set Version
        run: |
          COMMIT_HASH=$( git show --format='%h' --no-patch )
          vim package.json '+/"version"' '+s/:\s*".*\zs\ze"/+'$COMMIT_HASH/ '+wq'

      - name: Publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_SECRET }}
          tag: ${{ github.ref == 'refs/heads/aiscript-next' && 'next' || 'dev' }}
          provenance: true
          
